# Generated by Django 2.1.1 on 2018-11-20 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrared', '0003_auto_20181018_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infrared',
            name='manufacture',
            field=models.SmallIntegerField(choices=[(0, 'hao_li_shi'), (10, 'bang_qi'), (30, 'samsung_air_conditioner'), (9999999, 'dummy')]),
        ),
    ]
