# Generated by Django 2.1.1 on 2018-10-18 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'available'), (10, 'inuse'), (13, 'people in'), (20, 'cleaning'), (30, 'maintaining')]),
        ),
    ]
