# Generated by Django 2.1 on 2018-12-12 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_auto_20181018_1006'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True, db_index=True)),
                ('code', models.CharField(max_length=256)),
                ('code_name', models.CharField(max_length=256)),
                ('rt_rm', models.BooleanField()),
                ('equipment_type', models.PositiveSmallIntegerField(choices=[(0, '灯'), (10, '窗帘'), (20, '雾化玻璃'), (30, '门锁'), (40, '猫眼'), (50, '空调')])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True, db_index=True)),
                ('hid', models.IntegerField(help_text='Hotel ID from EFD_set', unique=True)),
                ('bangqi_url', models.URLField(null=True)),
                ('samsung_ac_url', models.URLField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('room_type_name', models.CharField(max_length=256)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='room.Hotel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RoomTypeCommand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True, db_index=True)),
                ('command', models.CharField(max_length=256)),
                ('equipment_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='room.EquipmentCode')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='room.RoomType')),
            ],
        ),
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='equipmentcode',
            name='equipment_hotel',
            field=models.ManyToManyField(to='room.Hotel'),
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='room.RoomType'),
        ),
    ]
