# Generated by Django 2.1 on 2021-08-28 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_auto_20181212_0518'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='roomtypecommand',
            unique_together={('room_type', 'equipment_name')},
        ),
    ]
