# Generated by Django 2.1.1 on 2018-10-31 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentcode',
            name='code',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='equipmentcode',
            name='code_name',
            field=models.CharField(max_length=256),
        ),
    ]
