# Generated by Django 2.1.1 on 2018-10-31 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_auto_20181031_1258'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EquipmentCode',
        ),
    ]
