# Generated by Django 2.0.7 on 2018-07-17 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirConditioner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True, db_index=True)),
                ('manufacture', models.SmallIntegerField(choices=[(0, 'hao shi lai'), (10, 'bang qi')])),
                ('manufacture_device_id', models.CharField(max_length=256)),
                ('is_on', models.NullBooleanField(default=None)),
                ('mode', models.SmallIntegerField(choices=[(0, 'not sure'),
                                                           (10, 'cold'), (20, 'warm'), (30, 'fan')], default=0)),
                ('temperature', models.SmallIntegerField(default=25)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='room.Room')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
