# Generated by Django 2.0 on 2018-09-21 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('air_conditioner', '0002_auto_20180921_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airconditioner',
            name='room_test',
        ),
    ]
