# Generated by Django 2.1.1 on 2018-11-21 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air_conditioner', '0003_remove_airconditioner_room_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='airconditioner',
            name='room_temperature',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='airconditioner',
            name='wind_direction',
            field=models.SmallIntegerField(choices=[(0, 'not sure'), (10, 'up and down'), (20, 'left and right'), (30, 'around'), (40, 'stop')], default=0),
        ),
        migrations.AddField(
            model_name='airconditioner',
            name='wind_speed',
            field=models.SmallIntegerField(choices=[(0, 'not sure'), (10, 'auto'), (20, 'slow'), (30, 'medium'), (40, 'quick')], default=0),
        ),
        migrations.AlterField(
            model_name='airconditioner',
            name='manufacture',
            field=models.SmallIntegerField(choices=[(0, 'hao_li_shi'), (10, 'bang_qi'), (30, 'samsung_air_conditioner'), (9999999, 'dummy')]),
        ),
        migrations.AlterField(
            model_name='airconditioner',
            name='mode',
            field=models.SmallIntegerField(choices=[(0, 'not sure'), (10, 'auto'), (20, 'cold'), (30, 'dehumidification'), (40, 'fan'), (50, 'warm')], default=0),
        ),
    ]
