# Generated by Django 2.1.1 on 2018-12-07 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('air_conditioner', '0004_auto_20181121_1043'),
        ('air_conditioner', '0004_auto_20181018_0933'),
    ]

    operations = [
    ]
