# Generated by Django 2.1 on 2018-12-12 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_auto_20181212_0518'),
        ('air_conditioner', '0005_merge_20181207_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airconditioner',
            name='manufacture',
            field=models.SmallIntegerField(choices=[(0, 'hao_li_shi'), (10, 'bang_qi'), (20, 'yi lu'), (30, 'samsung_air_conditioner'), (9999999, 'dummy')]),
        ),
    ]
