# Generated by Django 2.1 on 2021-08-28 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_auto_20210828_0213'),
        ('air_conditioner', '0006_auto_20181212_0518'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='airconditioner',
            unique_together={('manufacture', 'manufacture_device_id', 'room')},
        ),
    ]
