# Generated by Django 2.0.7 on 2018-07-17 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Light',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True, db_index=True)),
                ('manufacture', models.SmallIntegerField(choices=[(0, 'hao shi lai'), (10, 'bang qi')])),
                ('manufacture_device_id', models.CharField(max_length=256)),
                ('is_on', models.NullBooleanField(default=None)),
                ('position', models.SmallIntegerField(choices=[(0, 'other'), (10, 'entrance'), (20, 'toilet'), (30, 'bath room'), (
                    40, 'bed room main'), (50, 'reading on desk'), (60, 'by bed left'), (70, 'by bed right')], default=0)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='room.Room')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
