# Generated by Django 2.0 on 2018-09-21 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('light', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='light',
            name='room_test',
            field=models.CharField(default=0, max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='light',
            name='manufacture',
            field=models.SmallIntegerField(choices=[(0, 'hao li shi'), (10, 'bang qi')]),
        ),
    ]
