# Generated by Django 2.1.1 on 2018-12-07 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('light', '0004_auto_20181018_0933'),
        ('light', '0005_auto_20181018_2053'),
    ]

    operations = [
    ]
