# Generated by Django 2.1 on 2018-12-12 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_auto_20181212_0518'),
        ('light', '0006_merge_20181207_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='light',
            name='room_type_command',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='room.RoomTypeCommand'),
        ),
        migrations.AlterField(
            model_name='light',
            name='manufacture',
            field=models.SmallIntegerField(choices=[(0, 'hao_li_shi'), (10, 'bang_qi'), (20, 'yi lu'), (30, 'samsung_air_conditioner'), (9999999, 'dummy')]),
        ),
        migrations.AlterField(
            model_name='light',
            name='position',
            field=models.SmallIntegerField(choices=[(0, 'other'), (10, '夜灯'), (20, '廊灯'), (30, '卫生间灯'), (40, '主灯'), (50, '左壁灯'), (60, '右壁灯'), (70, '睡眠')], default=0),
        ),
        migrations.AlterUniqueTogether(
            name='light',
            unique_together={('room', 'room_type_command')},
        ),
    ]
