# Generated by Django 2.0.7 on 2018-09-11 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('room', '0002_auto_20181018_1006'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatEye',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True, db_index=True)),
                ('manufacture', models.SmallIntegerField(choices=[(0, 'hao shi lai'), (10, 'bang qi'), (9999999, 'dummy')])),
                ('manufacture_device_id', models.CharField(max_length=256)),
                ('private_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('push_id', models.CharField(blank=True, max_length=128)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='room.Room')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
