# Generated by Django 2.1 on 2018-12-27 09:13

from django.db import migrations
import semantic_version.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('cateye', '0002_auto_20181212_0518'),
    ]

    operations = [
        migrations.AddField(
            model_name='cateye',
            name='hardware_version',
            field=semantic_version.django_fields.VersionField(blank=True, coerce=True, max_length=200, null=True, partial=False),
        ),
        migrations.AddField(
            model_name='cateye',
            name='software_version',
            field=semantic_version.django_fields.VersionField(blank=True, coerce=True, max_length=200, null=True, partial=False),
        ),
    ]
