# Generated by Django 2.1 on 2018-12-27 11:02

from django.db import migrations, models
import semantic_version.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('cateye', '0003_add_versions'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatEyeSoftwareVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True, db_index=True)),
                ('version', semantic_version.django_fields.VersionField(coerce=True, max_length=200, partial=False)),
                ('apk', models.FileField(upload_to='cateye_software')),
                ('log', models.TextField(blank=True)),
                ('size', models.IntegerField(editable=False)),
                ('md5', models.CharField(editable=False, max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
