# Generated by Django 2.1 on 2019-01-02 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cateye', '0004_cateyesoftwareversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cateye',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
