# Generated by Django 2.1 on 2018-12-12 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('room', '0003_auto_20181212_0518'),
    ]

    operations = [
        migrations.CreateModel(
            name='Glass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True, db_index=True)),
                ('manufacture', models.SmallIntegerField(choices=[(0, 'hao_li_shi'), (10, 'bang_qi'), (20, 'yi lu'), (30, 'samsung_air_conditioner'), (9999999, 'dummy')])),
                ('manufacture_device_id', models.CharField(max_length=256)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='room.Room')),
                ('room_type_command', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='room.RoomTypeCommand')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='glass',
            unique_together={('room', 'room_type_command')},
        ),
    ]
